version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build:
    macos:
      xcode: "12.5.1"
    resource_class: medium
    steps:
      - checkout
      - node/install:
            node-version: "16.13.2"
      - run: node -v
      - node/install-packages:
          check-cache: always
          with-cache: false
      - run: npm run pw:circle

      - store_artifacts:
          path: ./pw_js/screenshots

workflows:
  version: 2
  workflow:
    jobs:
      - build