package models.gcp;

import com.microsoft.playwright.*;

public class CalculatorPage {
    private final Page page;

    public CalculatorPage(Page page) {
        this.page = page;
    }

    public Page getPage(){
        return this.page;
    }

    public void searchForCalcluator() {
        /**
         * Everything except `page.keyboard().press("Enter");` is generated by codegen 
         */

        // searchTermInput.fill(text);
        // searchTermInput.press("Enter");
         // Click [placeholder="Search"]
        page.locator("[placeholder=\"Search\"]").click();
        // Click [placeholder="Search"]
        page.locator("[placeholder=\"Search\"]").click();
        // Fill [placeholder="Search"]
        page.locator("[placeholder=\"Search\"]").fill("calculator");
        // Click #suggestion-partial-query-0 >> text=calculator
        page.keyboard().press("Enter");
        // assertThat(page).hasURL("https://cloud.google.com/s/results/?q=calculator");
        // Click text=Google Cloud Pricing Calculator >> nth=0
        page.locator("text=Google Cloud Pricing Calculator").first().click();
        // assertThat(page).hasURL("https://cloud.google.com/products/calculator");}
    }
}
