package models.gcp;

import com.microsoft.playwright.*;

public class MainPage {
    private final Page page;

    public MainPage(Page page) {
        this.page = page;
    }

    public Page getPage(){
        return this.page;
    }

    public void navigateToGCP() {
        page.navigate("https://cloud.google.com");
    }

    protected Locator calculatorElement(String locator){
        return page.frameLocator("devsite-iframe iframe")
        .frameLocator("#myFrame").locator(locator);
    }

    public MainPage searchForCalcluator() {
        /**
         * Everything except `page.keyboard().press("Enter");` is generated by codegen 
         */

        // searchTermInput.fill(text);
        // searchTermInput.press("Enter");
         // Click [placeholder="Search"]
        page.locator("[placeholder=\"Search\"]").click();
        // Click [placeholder="Search"]
        page.locator("[placeholder=\"Search\"]").click();
        // Fill [placeholder="Search"]
        page.locator("[placeholder=\"Search\"]").fill("calculator");
        // Click #suggestion-partial-query-0 >> text=calculator
        page.keyboard().press("Enter");
        // assertThat(page).hasURL("https://cloud.google.com/s/results/?q=calculator");
        // Click text=Google Cloud Pricing Calculator >> nth=0
        page.waitForSelector("text=Google Cloud Pricing Calculator");
        page.locator("text=Google Cloud Pricing Calculator").first().click();
        // assertThat(page).hasURL("https://cloud.google.com/products/calculator");}
        return this;
    }

    public MainPage setUpCloudMachine(){
        page.waitForSelector("devsite-iframe iframe");
        // Click text=Number of instances * Layer 1 ? >> [aria-label="quantity"]
        page.frameLocator("devsite-iframe iframe")
        .frameLocator("#myFrame")
        .locator("text=Number of instances * Layer 1 ? >> [aria-label=\"quantity\"]").click();
        // Fill text=Number of instances * Layer 1 ? >> [aria-label="quantity"]
        page.frameLocator("devsite-iframe iframe")
        .frameLocator("#myFrame")
        .locator("text=Number of instances * Layer 1 ? >> [aria-label=\"quantity\"]").fill("2");

        this.calculatorElement("[ng-model='listingCtrl.computeServer.os']").click();
        this.calculatorElement("[value='ubuntu-pro']").click();
        
        return this;
    }
}
